//try catch
void main(){
  try{
    int age;
    int dog=7;
    
  }catch(e){
   print('there was an error: ${e.toString()}'); 
  }
    
    finally{
      print('complete');
    }
}
